/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    start: string;
                    end: string;
                    doctorId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CalendarEntryDTO"][];
                    };
                };
                /** @description Invalid `doctorId` or `end` or `start` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["DoctorDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateDoctorRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["DoctorDTO"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["DoctorDTO"];
                    };
                };
                /** @description Invalid `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcare-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["HealthcareServiceDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateHealthcareServiceRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["HealthcareServiceDTO"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcare-services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["HealthcareServiceDTO"];
                    };
                };
                /** @description Invalid `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["SubmitIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["IntakeRequestDTO"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/appointed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    start?: string;
                    end?: string;
                    doctorId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AppointedIntakeRequestDTO"][];
                    };
                };
                /** @description Invalid `doctorId` or `end` or `start` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    start: string;
                    end: string;
                    doctorId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["IntakeRequestDTO"][];
                    };
                };
                /** @description Invalid `doctorId` or `end` or `start` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["IntakeRequestDTO"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["IntakeRequestDTO"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["IntakeRequestDTO"];
                    };
                };
                /** @description Invalid `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["AcceptIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `body` or `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CloseReasonRequestDTO"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `body` or `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}/mark-stale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["AvailableSlotDTO"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `body` or `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}/reclaim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["RejectIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `body` or `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["PatientDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreatePatientRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["PatientDTO"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["PatientDTO"];
                    };
                };
                /** @description Invalid `id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    start: string;
                    end: string;
                    doctorId?: string;
                    healthcareServiceId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AvailableSlotDTO"][];
                    };
                };
                /** @description Invalid `healthcareServiceId` or `doctorId` or `end` or `start` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateAvailableSlotRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["Value"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptIntakeRequestRequest: {
            healthcareServiceId: components["schemas"]["UUID"];
            priority: components["schemas"]["IntakeRequestPriorityDTO"];
        };
        AppointedIntakeRequestDTO: {
            createdAt: components["schemas"]["UTCTime"];
            doctorId: components["schemas"]["UUID"];
            doctorRequirement: components["schemas"]["DoctorRequirementDTO"];
            duration: components["schemas"]["DurationDTO"];
            healthcareServiceId: components["schemas"]["UUID"];
            id: components["schemas"]["UUID"];
            narrative: string;
            patientId: components["schemas"]["UUID"];
            priority: components["schemas"]["IntakeRequestPriorityDTO"];
            start: components["schemas"]["UTCTime"];
            triagedAt: components["schemas"]["UTCTime"];
        };
        AppointmentPartyDTO: {
            /** @enum {string} */
            type: "byDoctor" | "byPatient";
        };
        AvailableSlotDTO: {
            doctorId: components["schemas"]["UUID"];
            duration: components["schemas"]["DurationDTO"];
            healthcareServiceId: components["schemas"]["UUID"];
            id: components["schemas"]["UUID"];
            start: components["schemas"]["UTCTime"];
        };
        CalendarEntryDTO: {
            createdAt?: components["schemas"]["UTCTime"];
            doctorId: components["schemas"]["UUID"];
            doctorRequirement?: components["schemas"]["DoctorRequirementDTO"];
            duration: components["schemas"]["DurationDTO"];
            healthcareServiceId: components["schemas"]["UUID"];
            id: components["schemas"]["UUID"];
            narrative?: string;
            patientId?: components["schemas"]["UUID"];
            priority?: components["schemas"]["IntakeRequestPriorityDTO"];
            start: components["schemas"]["UTCTime"];
            triagedAt?: components["schemas"]["UTCTime"];
            /** @enum {string} */
            type: "slot" | "appointment";
        };
        CloseReasonDTO: {
            by?: components["schemas"]["AppointmentPartyDTO"];
            cancelledAt?: components["schemas"]["UTCTime"];
            note?: string;
            /** @enum {string} */
            type: "completed" | "cancelled" | "noShow";
        };
        CloseReasonRequestDTO: {
            by?: components["schemas"]["AppointmentPartyDTO"];
            note?: string;
            /** @enum {string} */
            type: "completed" | "cancelled" | "noShow";
        };
        CreateAvailableSlotRequest: {
            doctorId: components["schemas"]["UUID"];
            duration: components["schemas"]["DurationDTO"];
            healthcareServiceId: components["schemas"]["UUID"];
            start: components["schemas"]["UTCTime"];
        };
        CreateDoctorRequest: {
            name: string;
        };
        CreateHealthcareServiceRequest: {
            duration: components["schemas"]["DurationDTO"];
            name: string;
        };
        CreatePatientRequest: {
            name: string;
        };
        DoctorDTO: {
            id: components["schemas"]["UUID"];
            name: string;
        };
        DoctorRequirementDTO: {
            doctorId?: components["schemas"]["UUID"];
            /** @enum {string} */
            type: "anyDoctor" | "specificDoctor";
        };
        DurationDTO: {
            /** @enum {string} */
            type: "quarterOfAnHour" | "halfAnHour" | "oneHour";
        };
        HealthcareServiceDTO: {
            duration: components["schemas"]["DurationDTO"];
            id: components["schemas"]["UUID"];
            name: string;
        };
        IntakeRequestDTO: {
            closeReason?: components["schemas"]["CloseReasonDTO"];
            createdAt: components["schemas"]["UTCTime"];
            doctorId?: components["schemas"]["UUID"];
            doctorRequirement: components["schemas"]["DoctorRequirementDTO"];
            duration?: components["schemas"]["DurationDTO"];
            healthcareServiceId?: components["schemas"]["UUID"];
            id: components["schemas"]["UUID"];
            narrative: string;
            patientId: components["schemas"]["UUID"];
            priority?: components["schemas"]["IntakeRequestPriorityDTO"];
            rejectedAt?: components["schemas"]["UTCTime"];
            rejectionReason?: string;
            staleAt?: components["schemas"]["UTCTime"];
            start?: components["schemas"]["UTCTime"];
            triagedAt?: components["schemas"]["UTCTime"];
            /** @enum {string} */
            type: "submitted" | "rejected" | "accepted" | "appointed" | "withdrawnFromSubmitted" | "withdrawnFromAccepted" | "stale" | "closed";
            withdrawalNote?: string;
            withdrawnAt?: components["schemas"]["UTCTime"];
        };
        IntakeRequestPriorityDTO: {
            due: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            type: "emergency" | "urgent" | "routine";
        };
        PatientDTO: {
            id: components["schemas"]["UUID"];
            name: string;
        };
        RejectIntakeRequestRequest: {
            rejectionReason: string;
        };
        SubmitIntakeRequestRequest: {
            doctorRequirement: components["schemas"]["DoctorRequirementDTO"];
            narrative: string;
            patientId: components["schemas"]["UUID"];
        };
        /**
         * Format: yyyy-mm-ddThh:MM:ssZ
         * @example 2016-07-22T00:00:00Z
         */
        UTCTime: string;
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        UUID: string;
        Value: {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
