/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/available-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateAvailableSlotRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreateAvailableSlotAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/available-slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchAvailableSlotAnswer"];
                    };
                };
                /** @description Invalid `slotId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/available-slots/{slotId}/match-by-priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MatchAvailableSlotByPriorityAnswer"];
                    };
                };
                /** @description Invalid `slotId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchDoctorCalendarEntriesOverlappingAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchDoctorsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateDoctorRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreateDoctorAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{doctorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    doctorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchDoctorAnswer"];
                    };
                };
                /** @description Invalid `doctorId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcare-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchHealthcareServicesAnswer"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateHealthcareServiceRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreateHealthcareServiceAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcare-services/{healthcareServiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    healthcareServiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchHealthcareServiceAnswer"];
                    };
                };
                /** @description Invalid `healthcareServiceId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["SubmitIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["SubmitIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/accepted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchAcceptedIntakeRequestsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/appointed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchAppointedIntakeRequestsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchClosedIntakeRequestsByStartAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/rejected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchRejectedIntakeRequestsByRejectedAtAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/stale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchStaleIntakeRequestsByStaleAtAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchSubmittedIntakeRequestsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/withdrawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchWithdrawnIntakeRequestsByWithdrawnAtAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["AcceptSubmittedIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AcceptSubmittedIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` or `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CloseAppointedIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CloseAppointedIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` or `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/mark-stale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MarkAcceptedIntakeRequestStaleAnswer"];
                    };
                };
                /** @description Invalid `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/match-to-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["MatchAcceptedIntakeRequestToSlotRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswer"];
                    };
                };
                /** @description Invalid `body` or `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["RejectSubmittedIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RejectSubmittedIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` or `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["WithdrawIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["WithdrawIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` or `intakeRequestId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchPatientsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreatePatientRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreatePatientAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchPatientAnswer"];
                    };
                };
                /** @description Invalid `patientId` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptSubmittedIntakeRequestAnswer: {
            /** @description By outcome: transitioned: TriagedIntakeRequest; movedOn: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "transitioned" | "movedOn" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        AcceptSubmittedIntakeRequestRequest: {
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            priority: components["schemas"]["IntakeRequestPriority"];
        };
        AppointedIntakeRequest: {
            createdAt: components["schemas"]["UTCTime"];
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            start: components["schemas"]["UTCTime"];
            triagedAt: components["schemas"]["UTCTime"];
        };
        /** @description One object per case, told apart by "type". doctorParty: no other keys; patientParty: no other keys */
        AppointmentParty: {
            /** @enum {string} */
            type: "doctorParty" | "patientParty";
        };
        AvailableSlot: {
            doctorId: components["schemas"]["DoctorId"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["SlotId"];
            start: components["schemas"]["UTCTime"];
        };
        CloseAppointedIntakeRequestAnswer: {
            /** @description By outcome: transitioned: ClosedIntakeRequest; movedOn: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "transitioned" | "movedOn" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        CloseAppointedIntakeRequestRequest: {
            closeReason: components["schemas"]["CloseReasonRequest"];
        };
        /** @description One object per case, told apart by "type". completed: no other keys; cancelled: cancelledBy, cancelledAt, cancellationNote; noShow: absentParty */
        CloseReason: {
            absentParty?: components["schemas"]["AppointmentParty"];
            cancellationNote?: string;
            cancelledAt?: components["schemas"]["UTCTime"];
            cancelledBy?: components["schemas"]["AppointmentParty"];
            /** @enum {string} */
            type: "completed" | "cancelled" | "noShow";
        };
        /** @description One object per case, told apart by "type". completed: no other keys; cancelled: cancelledBy, cancellationNote; noShow: absentParty */
        CloseReasonRequest: {
            absentParty?: components["schemas"]["AppointmentParty"];
            cancellationNote?: string;
            cancelledBy?: components["schemas"]["AppointmentParty"];
            /** @enum {string} */
            type: "completed" | "cancelled" | "noShow";
        };
        ClosedIntakeRequest: {
            closeReason: components["schemas"]["CloseReason"];
            createdAt: components["schemas"]["UTCTime"];
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            start: components["schemas"]["UTCTime"];
            triagedAt: components["schemas"]["UTCTime"];
        };
        CreateAvailableSlotAnswer: {
            /** @description By outcome: slotCreated: AvailableSlot; slotOverlapsDoctorCalendar: null; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "slotCreated" | "slotOverlapsDoctorCalendar" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        CreateAvailableSlotRequest: {
            doctorId: components["schemas"]["DoctorId"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            start: components["schemas"]["UTCTime"];
        };
        CreateDoctorAnswer: {
            /** @description By outcome: ok: Doctor */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok";
        };
        CreateDoctorRequest: {
            name: string;
        };
        CreateHealthcareServiceAnswer: {
            /** @description By outcome: ok: HealthcareService */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok";
        };
        CreateHealthcareServiceRequest: {
            duration: components["schemas"]["Duration"];
            name: string;
        };
        CreatePatientAnswer: {
            /** @description By outcome: ok: Patient */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok";
        };
        CreatePatientRequest: {
            name: string;
        };
        Doctor: {
            id: components["schemas"]["DoctorId"];
            name: string;
        };
        /** @description One object per case, told apart by "type". slot: id, doctorId, healthcareServiceId, start, duration; appointment: id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt, doctorId, start, duration */
        DoctorCalendarEntry: {
            createdAt?: components["schemas"]["UTCTime"];
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement?: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["SlotId"];
            narrative?: string;
            patientId?: components["schemas"]["PatientId"];
            priority?: components["schemas"]["IntakeRequestPriority"];
            start: components["schemas"]["UTCTime"];
            triagedAt?: components["schemas"]["UTCTime"];
            /** @enum {string} */
            type: "slot" | "appointment";
        };
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        DoctorId: string;
        /** @description One object per case, told apart by "type". anyDoctor: no other keys; specificDoctor: specificDoctor */
        DoctorRequirement: {
            specificDoctor?: components["schemas"]["DoctorId"];
            /** @enum {string} */
            type: "anyDoctor" | "specificDoctor";
        };
        /** @description One object per case, told apart by "type". quarterOfAnHour: no other keys; halfAnHour: no other keys; oneHour: no other keys */
        Duration: {
            /** @enum {string} */
            type: "quarterOfAnHour" | "halfAnHour" | "oneHour";
        };
        FetchAcceptedIntakeRequestsAnswer: {
            /** @description By outcome: ok: array of TriagedIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchAppointedIntakeRequestsAnswer: {
            /** @description By outcome: ok: array of AppointedIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchAvailableSlotAnswer: {
            /** @description By outcome: ok: AvailableSlot; availableSlotConsumed: null; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "availableSlotConsumed" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchClosedIntakeRequestsByStartAnswer: {
            /** @description By outcome: ok: array of ClosedIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchDoctorAnswer: {
            /** @description By outcome: ok: Doctor; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchDoctorCalendarEntriesOverlappingAnswer: {
            /** @description By outcome: ok: array of DoctorCalendarEntry; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchDoctorsAnswer: {
            /** @description By outcome: ok: array of Doctor */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok";
        };
        FetchHealthcareServiceAnswer: {
            /** @description By outcome: ok: HealthcareService; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchHealthcareServicesAnswer: {
            /** @description By outcome: ok: array of HealthcareService; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchIntakeRequestAnswer: {
            /** @description By outcome: ok: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchPatientAnswer: {
            /** @description By outcome: ok: Patient; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchPatientsAnswer: {
            /** @description By outcome: ok: array of Patient */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok";
        };
        FetchRejectedIntakeRequestsByRejectedAtAnswer: {
            /** @description By outcome: ok: array of RejectedIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchStaleIntakeRequestsByStaleAtAnswer: {
            /** @description By outcome: ok: array of StaleIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchSubmittedIntakeRequestsAnswer: {
            /** @description By outcome: ok: array of SubmittedIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        FetchWithdrawnIntakeRequestsByWithdrawnAtAnswer: {
            /** @description By outcome: ok: array of WithdrawnIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        HealthcareService: {
            duration: components["schemas"]["Duration"];
            id: components["schemas"]["HealthcareServiceId"];
            name: string;
        };
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        HealthcareServiceId: string;
        /** @description One object per case, told apart by "type". submitted: id, patientId, narrative, createdAt; rejected: id, patientId, narrative, createdAt, rejectedAt, rejectionReason; accepted: id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt; appointed: id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt, doctorId, start, duration; withdrawn: withdrawnFrom, id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt, withdrawnAt, withdrawalNote; stale: id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt, staleAt; closed: id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt, doctorId, start, duration, closeReason */
        IntakeRequest: {
            closeReason?: components["schemas"]["CloseReason"];
            createdAt: components["schemas"]["UTCTime"];
            doctorId?: components["schemas"]["DoctorId"];
            doctorRequirement?: components["schemas"]["DoctorRequirement"];
            duration?: components["schemas"]["Duration"];
            healthcareServiceId?: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority?: components["schemas"]["IntakeRequestPriority"];
            rejectedAt?: components["schemas"]["UTCTime"];
            rejectionReason?: string;
            staleAt?: components["schemas"]["UTCTime"];
            start?: components["schemas"]["UTCTime"];
            triagedAt?: components["schemas"]["UTCTime"];
            /** @enum {string} */
            type: "submitted" | "rejected" | "accepted" | "appointed" | "withdrawn" | "stale" | "closed";
            withdrawalNote?: string;
            withdrawnAt?: components["schemas"]["UTCTime"];
            withdrawnFrom?: {
                /** @enum {string} */
                type: "fromSubmitted" | "fromAccepted";
            };
        };
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        IntakeRequestId: string;
        /** @description One object per case, told apart by "type". emergency: mustBeSeenBy; urgent: mustBeSeenBy; routine: routine */
        IntakeRequestPriority: {
            mustBeSeenBy?: components["schemas"]["UTCTime"];
            routine?: components["schemas"]["RoutineDue"];
            /** @enum {string} */
            type: "emergency" | "urgent" | "routine";
        };
        MarkAcceptedIntakeRequestStaleAnswer: {
            /** @description By outcome: transitioned: StaleIntakeRequest; movedOn: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "transitioned" | "movedOn" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        MatchAcceptedIntakeRequestToSlotAnswer: {
            /** @description By outcome: matched: AppointedIntakeRequest; availableSlotConsumed: null; intakeRequestMovedOn: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "matched" | "availableSlotConsumed" | "intakeRequestMovedOn" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        MatchAcceptedIntakeRequestToSlotRequest: {
            slotId: components["schemas"]["SlotId"];
        };
        MatchAvailableSlotByPriorityAnswer: {
            /** @description By outcome: noMatchingIntakeRequest: null; matchAttempted: MatchOutcome; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "noMatchingIntakeRequest" | "matchAttempted" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        MatchOutcome: {
            /** @description By outcome: matched: AppointedIntakeRequest; availableSlotConsumed: null; intakeRequestMovedOn: IntakeRequest */
            detail: unknown;
            /** @enum {string} */
            outcome: "matched" | "availableSlotConsumed" | "intakeRequestMovedOn";
        };
        Patient: {
            id: components["schemas"]["PatientId"];
            name: string;
        };
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        PatientId: string;
        RejectSubmittedIntakeRequestAnswer: {
            /** @description By outcome: transitioned: RejectedIntakeRequest; movedOn: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "transitioned" | "movedOn" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        RejectSubmittedIntakeRequestRequest: {
            rejectionReason: string;
        };
        RejectedIntakeRequest: {
            createdAt: components["schemas"]["UTCTime"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            rejectedAt: components["schemas"]["UTCTime"];
            rejectionReason: string;
        };
        /** @description One object per case, told apart by "type". routineAnytime: no other keys; routineNotBefore: routineNotBefore; routineNotAfter: routineNotAfter; routineWithin: routineNotBefore, routineNotAfter */
        RoutineDue: {
            routineNotAfter?: components["schemas"]["UTCTime"];
            routineNotBefore?: components["schemas"]["UTCTime"];
            /** @enum {string} */
            type: "routineAnytime" | "routineNotBefore" | "routineNotAfter" | "routineWithin";
        };
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        SlotId: string;
        StaleIntakeRequest: {
            createdAt: components["schemas"]["UTCTime"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            staleAt: components["schemas"]["UTCTime"];
            triagedAt: components["schemas"]["UTCTime"];
        };
        SubmitIntakeRequestAnswer: {
            /** @description By outcome: ok: SubmittedIntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "ok" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        SubmitIntakeRequestRequest: {
            narrative: string;
            patientId: components["schemas"]["PatientId"];
        };
        SubmittedIntakeRequest: {
            createdAt: components["schemas"]["UTCTime"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
        };
        TriagedIntakeRequest: {
            createdAt: components["schemas"]["UTCTime"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            triagedAt: components["schemas"]["UTCTime"];
        };
        /**
         * Format: yyyy-mm-ddThh:MM:ssZ
         * @example 2016-07-22T00:00:00Z
         */
        UTCTime: string;
        WithdrawIntakeRequestAnswer: {
            /** @description By outcome: transitioned: WithdrawnIntakeRequest; movedOn: IntakeRequest; doctorNotFound: DoctorId; patientNotFound: PatientId; healthcareServiceNotFound: HealthcareServiceId; intakeRequestNotFound: IntakeRequestId; intakeRequestInWrongState: IntakeRequest; slotDoesNotMatchIntakeRequest: null */
            detail: unknown;
            /** @enum {string} */
            outcome: "transitioned" | "movedOn" | "doctorNotFound" | "patientNotFound" | "healthcareServiceNotFound" | "intakeRequestNotFound" | "intakeRequestInWrongState" | "slotDoesNotMatchIntakeRequest";
        };
        WithdrawIntakeRequestRequest: {
            withdrawalNote?: string;
        };
        /** @description Keys of the stage it was withdrawn from, by withdrawnFrom.type. fromSubmitted: id, patientId, narrative, createdAt; fromAccepted: id, patientId, narrative, createdAt, healthcareServiceId, priority, doctorRequirement, triagedAt */
        WithdrawnIntakeRequest: {
            createdAt: components["schemas"]["UTCTime"];
            doctorRequirement?: components["schemas"]["DoctorRequirement"];
            healthcareServiceId?: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority?: components["schemas"]["IntakeRequestPriority"];
            triagedAt?: components["schemas"]["UTCTime"];
            withdrawalNote?: string;
            withdrawnAt: components["schemas"]["UTCTime"];
            withdrawnFrom: {
                /** @enum {string} */
                type: "fromSubmitted" | "fromAccepted";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
