/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/available-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateAvailableSlotRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreateAvailableSlotAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/available-slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchAvailableSlotAnswer"];
                    };
                };
                /** @description `slotId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/available-slots/{slotId}/match-by-priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MatchAvailableSlotByPriorityAnswer"];
                    };
                };
                /** @description `slotId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchDoctorCalendarEntriesOverlappingAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchDoctorsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateDoctorRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreateDoctorAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{doctorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    doctorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchDoctorAnswer"];
                    };
                };
                /** @description `doctorId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcare-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchHealthcareServicesAnswer"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreateHealthcareServiceRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreateHealthcareServiceAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcare-services/{healthcareServiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    healthcareServiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchHealthcareServiceAnswer"];
                    };
                };
                /** @description `healthcareServiceId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["SubmitIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["SubmitIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/accepted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchAcceptedIntakeRequestsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/appointed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchAppointedIntakeRequestsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchClosedIntakeRequestsByStartAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/rejected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchRejectedIntakeRequestsByRejectedAtAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/stale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchStaleIntakeRequestsByStaleAtAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchSubmittedIntakeRequestsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/withdrawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchWithdrawnIntakeRequestsByWithdrawnAtAnswer"];
                    };
                };
                /** @description Invalid `to` or `from` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchIntakeRequestAnswer"];
                    };
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["AcceptSubmittedIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AcceptSubmittedIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CloseAppointedIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CloseAppointedIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/mark-stale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MarkAcceptedIntakeRequestStaleAnswer"];
                    };
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/match-to-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["MatchAcceptedIntakeRequestToSlotRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["RejectSubmittedIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RejectSubmittedIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake-requests/{intakeRequestId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intakeRequestId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["WithdrawIntakeRequestRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["WithdrawIntakeRequestAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `intakeRequestId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchPatientsAnswer"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CreatePatientRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CreatePatientAnswer"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["FetchPatientAnswer"];
                    };
                };
                /** @description `patientId` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptSubmittedIntakeRequestAnswer: components["schemas"]["AcceptSubmittedIntakeRequestAnswerTransitioned"] | components["schemas"]["AcceptSubmittedIntakeRequestAnswerMovedOn"] | components["schemas"]["AcceptSubmittedIntakeRequestAnswerIntakeRequestNotFound"] | components["schemas"]["AcceptSubmittedIntakeRequestAnswerHealthcareServiceNotFound"] | components["schemas"]["AcceptSubmittedIntakeRequestAnswerDoctorNotFound"];
        AcceptSubmittedIntakeRequestAnswerDoctorNotFound: {
            detail: components["schemas"]["DoctorId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "doctorNotFound";
        };
        AcceptSubmittedIntakeRequestAnswerHealthcareServiceNotFound: {
            detail: components["schemas"]["HealthcareServiceId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "healthcareServiceNotFound";
        };
        AcceptSubmittedIntakeRequestAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        AcceptSubmittedIntakeRequestAnswerMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "movedOn";
        };
        AcceptSubmittedIntakeRequestAnswerTransitioned: {
            detail: components["schemas"]["TriagedIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "transitioned";
        };
        AcceptSubmittedIntakeRequestRequest: {
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            priority: components["schemas"]["IntakeRequestPriority"];
        };
        AppointedIntakeRequest: {
            /** Format: date-time */
            createdAt: string;
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            triagedAt: string;
        };
        AppointmentParty: {
            /** @enum {string} */
            type: "doctorParty" | "patientParty";
        };
        AvailableSlot: {
            doctorId: components["schemas"]["DoctorId"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["SlotId"];
            /** Format: date-time */
            start: string;
        };
        CloseAppointedIntakeRequestAnswer: components["schemas"]["CloseAppointedIntakeRequestAnswerTransitioned"] | components["schemas"]["CloseAppointedIntakeRequestAnswerMovedOn"] | components["schemas"]["CloseAppointedIntakeRequestAnswerIntakeRequestNotFound"] | components["schemas"]["CloseAppointedIntakeRequestAnswerIntakeRequestInWrongState"];
        CloseAppointedIntakeRequestAnswerIntakeRequestInWrongState: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestInWrongState";
        };
        CloseAppointedIntakeRequestAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        CloseAppointedIntakeRequestAnswerMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "movedOn";
        };
        CloseAppointedIntakeRequestAnswerTransitioned: {
            detail: components["schemas"]["ClosedIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "transitioned";
        };
        CloseAppointedIntakeRequestRequest: {
            closeReason: components["schemas"]["CloseReasonRequest"];
        };
        CloseReason: components["schemas"]["CloseReasonCompleted"] | components["schemas"]["CloseReasonCancelled"] | components["schemas"]["CloseReasonNoShow"];
        CloseReasonCancelled: {
            cancellationNote: string | null;
            /** Format: date-time */
            cancelledAt: string;
            cancelledBy: components["schemas"]["AppointmentParty"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cancelled";
        };
        CloseReasonCompleted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "completed";
        };
        CloseReasonNoShow: {
            absentParty: components["schemas"]["AppointmentParty"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noShow";
        };
        CloseReasonRequest: components["schemas"]["CloseReasonRequestCompleted"] | components["schemas"]["CloseReasonRequestCancelled"] | components["schemas"]["CloseReasonRequestNoShow"];
        CloseReasonRequestCancelled: {
            cancellationNote: string | null;
            cancelledBy: components["schemas"]["AppointmentParty"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cancelled";
        };
        CloseReasonRequestCompleted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "completed";
        };
        CloseReasonRequestNoShow: {
            absentParty: components["schemas"]["AppointmentParty"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noShow";
        };
        ClosedIntakeRequest: {
            closeReason: components["schemas"]["CloseReason"];
            /** Format: date-time */
            createdAt: string;
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            triagedAt: string;
        };
        CreateAvailableSlotAnswer: components["schemas"]["CreateAvailableSlotAnswerAvailableSlotAdded"] | components["schemas"]["CreateAvailableSlotAnswerAvailableSlotOverlapsDoctorCalendar"] | components["schemas"]["CreateAvailableSlotAnswerDoctorNotFound"] | components["schemas"]["CreateAvailableSlotAnswerHealthcareServiceNotFound"];
        CreateAvailableSlotAnswerAvailableSlotAdded: {
            detail: components["schemas"]["AvailableSlot"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "availableSlotAdded";
        };
        CreateAvailableSlotAnswerAvailableSlotOverlapsDoctorCalendar: {
            /** @enum {unknown|null} */
            detail: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "availableSlotOverlapsDoctorCalendar";
        };
        CreateAvailableSlotAnswerDoctorNotFound: {
            detail: components["schemas"]["DoctorId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "doctorNotFound";
        };
        CreateAvailableSlotAnswerHealthcareServiceNotFound: {
            detail: components["schemas"]["HealthcareServiceId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "healthcareServiceNotFound";
        };
        CreateAvailableSlotRequest: {
            doctorId: components["schemas"]["DoctorId"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            /** Format: date-time */
            start: string;
        };
        CreateDoctorAnswer: components["schemas"]["CreateDoctorAnswerOk"];
        CreateDoctorAnswerOk: {
            detail: components["schemas"]["Doctor"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        CreateDoctorRequest: {
            name: string;
        };
        CreateHealthcareServiceAnswer: components["schemas"]["CreateHealthcareServiceAnswerOk"];
        CreateHealthcareServiceAnswerOk: {
            detail: components["schemas"]["HealthcareService"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        CreateHealthcareServiceRequest: {
            duration: components["schemas"]["Duration"];
            name: string;
        };
        CreatePatientAnswer: components["schemas"]["CreatePatientAnswerOk"];
        CreatePatientAnswerOk: {
            detail: components["schemas"]["Patient"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        CreatePatientRequest: {
            name: string;
        };
        Doctor: {
            id: components["schemas"]["DoctorId"];
            name: string;
        };
        DoctorCalendarEntry: components["schemas"]["DoctorCalendarEntrySlot"] | components["schemas"]["DoctorCalendarEntryAppointment"];
        DoctorCalendarEntryAppointment: {
            /** Format: date-time */
            createdAt: string;
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            triagedAt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "appointment";
        };
        DoctorCalendarEntrySlot: {
            doctorId: components["schemas"]["DoctorId"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["SlotId"];
            /** Format: date-time */
            start: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "slot";
        };
        /** Format: uuid */
        DoctorId: string;
        DoctorRequirement: components["schemas"]["DoctorRequirementAnyDoctor"] | components["schemas"]["DoctorRequirementSpecificDoctor"];
        DoctorRequirementAnyDoctor: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "anyDoctor";
        };
        DoctorRequirementSpecificDoctor: {
            specificDoctor: components["schemas"]["DoctorId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "specificDoctor";
        };
        Duration: {
            /** @enum {string} */
            type: "quarterOfAnHour" | "halfAnHour" | "oneHour";
        };
        FetchAcceptedIntakeRequestsAnswer: components["schemas"]["FetchAcceptedIntakeRequestsAnswerOk"];
        FetchAcceptedIntakeRequestsAnswerOk: {
            detail: components["schemas"]["TriagedIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchAppointedIntakeRequestsAnswer: components["schemas"]["FetchAppointedIntakeRequestsAnswerOk"];
        FetchAppointedIntakeRequestsAnswerOk: {
            detail: components["schemas"]["AppointedIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchAvailableSlotAnswer: components["schemas"]["FetchAvailableSlotAnswerOk"] | components["schemas"]["FetchAvailableSlotAnswerAvailableSlotConsumed"];
        FetchAvailableSlotAnswerAvailableSlotConsumed: {
            detail: components["schemas"]["SlotId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "availableSlotConsumed";
        };
        FetchAvailableSlotAnswerOk: {
            detail: components["schemas"]["AvailableSlot"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchClosedIntakeRequestsByStartAnswer: components["schemas"]["FetchClosedIntakeRequestsByStartAnswerOk"];
        FetchClosedIntakeRequestsByStartAnswerOk: {
            detail: components["schemas"]["ClosedIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchDoctorAnswer: components["schemas"]["FetchDoctorAnswerOk"] | components["schemas"]["FetchDoctorAnswerDoctorNotFound"];
        FetchDoctorAnswerDoctorNotFound: {
            detail: components["schemas"]["DoctorId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "doctorNotFound";
        };
        FetchDoctorAnswerOk: {
            detail: components["schemas"]["Doctor"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchDoctorCalendarEntriesOverlappingAnswer: components["schemas"]["FetchDoctorCalendarEntriesOverlappingAnswerOk"];
        FetchDoctorCalendarEntriesOverlappingAnswerOk: {
            detail: components["schemas"]["DoctorCalendarEntry"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchDoctorsAnswer: components["schemas"]["FetchDoctorsAnswerOk"];
        FetchDoctorsAnswerOk: {
            detail: components["schemas"]["Doctor"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchHealthcareServiceAnswer: components["schemas"]["FetchHealthcareServiceAnswerOk"] | components["schemas"]["FetchHealthcareServiceAnswerHealthcareServiceNotFound"];
        FetchHealthcareServiceAnswerHealthcareServiceNotFound: {
            detail: components["schemas"]["HealthcareServiceId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "healthcareServiceNotFound";
        };
        FetchHealthcareServiceAnswerOk: {
            detail: components["schemas"]["HealthcareService"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchHealthcareServicesAnswer: components["schemas"]["FetchHealthcareServicesAnswerOk"];
        FetchHealthcareServicesAnswerOk: {
            detail: components["schemas"]["HealthcareService"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchIntakeRequestAnswer: components["schemas"]["FetchIntakeRequestAnswerOk"] | components["schemas"]["FetchIntakeRequestAnswerIntakeRequestNotFound"];
        FetchIntakeRequestAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        FetchIntakeRequestAnswerOk: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchPatientAnswer: components["schemas"]["FetchPatientAnswerOk"] | components["schemas"]["FetchPatientAnswerPatientNotFound"];
        FetchPatientAnswerOk: {
            detail: components["schemas"]["Patient"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchPatientAnswerPatientNotFound: {
            detail: components["schemas"]["PatientId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "patientNotFound";
        };
        FetchPatientsAnswer: components["schemas"]["FetchPatientsAnswerOk"];
        FetchPatientsAnswerOk: {
            detail: components["schemas"]["Patient"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchRejectedIntakeRequestsByRejectedAtAnswer: components["schemas"]["FetchRejectedIntakeRequestsByRejectedAtAnswerOk"];
        FetchRejectedIntakeRequestsByRejectedAtAnswerOk: {
            detail: components["schemas"]["RejectedIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchStaleIntakeRequestsByStaleAtAnswer: components["schemas"]["FetchStaleIntakeRequestsByStaleAtAnswerOk"];
        FetchStaleIntakeRequestsByStaleAtAnswerOk: {
            detail: components["schemas"]["StaleIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchSubmittedIntakeRequestsAnswer: components["schemas"]["FetchSubmittedIntakeRequestsAnswerOk"];
        FetchSubmittedIntakeRequestsAnswerOk: {
            detail: components["schemas"]["SubmittedIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        FetchWithdrawnIntakeRequestsByWithdrawnAtAnswer: components["schemas"]["FetchWithdrawnIntakeRequestsByWithdrawnAtAnswerOk"];
        FetchWithdrawnIntakeRequestsByWithdrawnAtAnswerOk: {
            detail: components["schemas"]["WithdrawnIntakeRequest"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        HealthcareService: {
            duration: components["schemas"]["Duration"];
            id: components["schemas"]["HealthcareServiceId"];
            name: string;
        };
        /** Format: uuid */
        HealthcareServiceId: string;
        IntakeRequest: components["schemas"]["IntakeRequestSubmitted"] | components["schemas"]["IntakeRequestRejected"] | components["schemas"]["IntakeRequestAccepted"] | components["schemas"]["IntakeRequestAppointed"] | components["schemas"]["IntakeRequestWithdrawn"] | components["schemas"]["IntakeRequestStale"] | components["schemas"]["IntakeRequestClosed"];
        IntakeRequestAccepted: {
            /** Format: date-time */
            createdAt: string;
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            triagedAt: string;
            /** @enum {string} */
            type: "accepted";
        };
        IntakeRequestAppointed: {
            /** Format: date-time */
            createdAt: string;
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            triagedAt: string;
            /** @enum {string} */
            type: "appointed";
        };
        IntakeRequestClosed: {
            closeReason: components["schemas"]["CloseReason"];
            /** Format: date-time */
            createdAt: string;
            doctorId: components["schemas"]["DoctorId"];
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            duration: components["schemas"]["Duration"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            triagedAt: string;
            /** @enum {string} */
            type: "closed";
        };
        /** Format: uuid */
        IntakeRequestId: string;
        IntakeRequestPriority: components["schemas"]["IntakeRequestPriorityEmergency"] | components["schemas"]["IntakeRequestPriorityUrgent"] | components["schemas"]["IntakeRequestPriorityRoutine"];
        IntakeRequestPriorityEmergency: {
            /** Format: date-time */
            mustBeSeenBy: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "emergency";
        };
        IntakeRequestPriorityRoutine: {
            routine: components["schemas"]["RoutineDue"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "routine";
        };
        IntakeRequestPriorityUrgent: {
            /** Format: date-time */
            mustBeSeenBy: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "urgent";
        };
        IntakeRequestRejected: {
            /** Format: date-time */
            createdAt: string;
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            /** Format: date-time */
            rejectedAt: string;
            rejectionReason: string;
            /** @enum {string} */
            type: "rejected";
        };
        IntakeRequestStale: {
            /** Format: date-time */
            createdAt: string;
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            staleAt: string;
            /** Format: date-time */
            triagedAt: string;
            /** @enum {string} */
            type: "stale";
        };
        IntakeRequestSubmitted: {
            /** Format: date-time */
            createdAt: string;
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            /** @enum {string} */
            type: "submitted";
        };
        IntakeRequestWithdrawn: components["schemas"]["IntakeRequestWithdrawnFromSubmitted"] | components["schemas"]["IntakeRequestWithdrawnFromAccepted"];
        IntakeRequestWithdrawnFromAccepted: {
            /** Format: date-time */
            createdAt: string;
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            triagedAt: string;
            /** @enum {string} */
            type: "withdrawn";
            withdrawalNote: string | null;
            /** Format: date-time */
            withdrawnAt: string;
            withdrawnFrom: {
                /** @enum {string} */
                type: "fromAccepted";
            };
        };
        IntakeRequestWithdrawnFromSubmitted: {
            /** Format: date-time */
            createdAt: string;
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            /** @enum {string} */
            type: "withdrawn";
            withdrawalNote: string | null;
            /** Format: date-time */
            withdrawnAt: string;
            withdrawnFrom: {
                /** @enum {string} */
                type: "fromSubmitted";
            };
        };
        MarkAcceptedIntakeRequestStaleAnswer: components["schemas"]["MarkAcceptedIntakeRequestStaleAnswerTransitioned"] | components["schemas"]["MarkAcceptedIntakeRequestStaleAnswerMovedOn"] | components["schemas"]["MarkAcceptedIntakeRequestStaleAnswerIntakeRequestNotFound"] | components["schemas"]["MarkAcceptedIntakeRequestStaleAnswerIntakeRequestInWrongState"];
        MarkAcceptedIntakeRequestStaleAnswerIntakeRequestInWrongState: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestInWrongState";
        };
        MarkAcceptedIntakeRequestStaleAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        MarkAcceptedIntakeRequestStaleAnswerMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "movedOn";
        };
        MarkAcceptedIntakeRequestStaleAnswerTransitioned: {
            detail: components["schemas"]["StaleIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "transitioned";
        };
        MatchAcceptedIntakeRequestToSlotAnswer: components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestMatchedToSlot"] | components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswerAvailableSlotConsumed"] | components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestMovedOn"] | components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestNotFound"] | components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestInWrongState"] | components["schemas"]["MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestDoesNotMatchSlot"];
        MatchAcceptedIntakeRequestToSlotAnswerAvailableSlotConsumed: {
            detail: components["schemas"]["SlotId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "availableSlotConsumed";
        };
        MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestDoesNotMatchSlot: {
            /** @enum {unknown|null} */
            detail: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestDoesNotMatchSlot";
        };
        MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestInWrongState: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestInWrongState";
        };
        MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestMatchedToSlot: {
            detail: components["schemas"]["AppointedIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestMatchedToSlot";
        };
        MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestMovedOn";
        };
        MatchAcceptedIntakeRequestToSlotAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        MatchAcceptedIntakeRequestToSlotRequest: {
            slotId: components["schemas"]["SlotId"];
        };
        MatchAvailableSlotByPriorityAnswer: components["schemas"]["MatchAvailableSlotByPriorityAnswerNoIntakeRequestMatched"] | components["schemas"]["MatchAvailableSlotByPriorityAnswerMatchIntakeRequestToSlotOutcome"];
        MatchAvailableSlotByPriorityAnswerMatchIntakeRequestToSlotOutcome: {
            detail: components["schemas"]["MatchIntakeRequestToSlotOutcome"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "matchIntakeRequestToSlotOutcome";
        };
        MatchAvailableSlotByPriorityAnswerNoIntakeRequestMatched: {
            /** @enum {unknown|null} */
            detail: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "noIntakeRequestMatched";
        };
        MatchIntakeRequestToSlotOutcome: components["schemas"]["MatchIntakeRequestToSlotOutcomeIntakeRequestMatchedToSlot"] | components["schemas"]["MatchIntakeRequestToSlotOutcomeAvailableSlotConsumed"] | components["schemas"]["MatchIntakeRequestToSlotOutcomeIntakeRequestMovedOn"];
        MatchIntakeRequestToSlotOutcomeAvailableSlotConsumed: {
            detail: components["schemas"]["SlotId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "availableSlotConsumed";
        };
        MatchIntakeRequestToSlotOutcomeIntakeRequestMatchedToSlot: {
            detail: components["schemas"]["AppointedIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestMatchedToSlot";
        };
        MatchIntakeRequestToSlotOutcomeIntakeRequestMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestMovedOn";
        };
        Patient: {
            id: components["schemas"]["PatientId"];
            name: string;
        };
        /** Format: uuid */
        PatientId: string;
        RejectSubmittedIntakeRequestAnswer: components["schemas"]["RejectSubmittedIntakeRequestAnswerTransitioned"] | components["schemas"]["RejectSubmittedIntakeRequestAnswerMovedOn"] | components["schemas"]["RejectSubmittedIntakeRequestAnswerIntakeRequestNotFound"];
        RejectSubmittedIntakeRequestAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        RejectSubmittedIntakeRequestAnswerMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "movedOn";
        };
        RejectSubmittedIntakeRequestAnswerTransitioned: {
            detail: components["schemas"]["RejectedIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "transitioned";
        };
        RejectSubmittedIntakeRequestRequest: {
            rejectionReason: string;
        };
        RejectedIntakeRequest: {
            /** Format: date-time */
            createdAt: string;
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            /** Format: date-time */
            rejectedAt: string;
            rejectionReason: string;
        };
        RoutineDue: components["schemas"]["RoutineDueRoutineAnytime"] | components["schemas"]["RoutineDueRoutineNotBefore"] | components["schemas"]["RoutineDueRoutineNotAfter"] | components["schemas"]["RoutineDueRoutineWithin"];
        RoutineDueRoutineAnytime: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "routineAnytime";
        };
        RoutineDueRoutineNotAfter: {
            /** Format: date-time */
            routineNotAfter: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "routineNotAfter";
        };
        RoutineDueRoutineNotBefore: {
            /** Format: date-time */
            routineNotBefore: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "routineNotBefore";
        };
        RoutineDueRoutineWithin: {
            /** Format: date-time */
            routineNotAfter: string;
            /** Format: date-time */
            routineNotBefore: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "routineWithin";
        };
        /** Format: uuid */
        SlotId: string;
        StaleIntakeRequest: {
            /** Format: date-time */
            createdAt: string;
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            staleAt: string;
            /** Format: date-time */
            triagedAt: string;
        };
        SubmitIntakeRequestAnswer: components["schemas"]["SubmitIntakeRequestAnswerOk"] | components["schemas"]["SubmitIntakeRequestAnswerPatientNotFound"];
        SubmitIntakeRequestAnswerOk: {
            detail: components["schemas"]["SubmittedIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "ok";
        };
        SubmitIntakeRequestAnswerPatientNotFound: {
            detail: components["schemas"]["PatientId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "patientNotFound";
        };
        SubmitIntakeRequestRequest: {
            narrative: string;
            patientId: components["schemas"]["PatientId"];
        };
        SubmittedIntakeRequest: {
            /** Format: date-time */
            createdAt: string;
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
        };
        TriagedIntakeRequest: {
            /** Format: date-time */
            createdAt: string;
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            triagedAt: string;
        };
        WithdrawIntakeRequestAnswer: components["schemas"]["WithdrawIntakeRequestAnswerTransitioned"] | components["schemas"]["WithdrawIntakeRequestAnswerMovedOn"] | components["schemas"]["WithdrawIntakeRequestAnswerIntakeRequestNotFound"];
        WithdrawIntakeRequestAnswerIntakeRequestNotFound: {
            detail: components["schemas"]["IntakeRequestId"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "intakeRequestNotFound";
        };
        WithdrawIntakeRequestAnswerMovedOn: {
            detail: components["schemas"]["IntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "movedOn";
        };
        WithdrawIntakeRequestAnswerTransitioned: {
            detail: components["schemas"]["WithdrawnIntakeRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "transitioned";
        };
        WithdrawIntakeRequestRequest: {
            withdrawalNote: string | null;
        };
        WithdrawnIntakeRequest: components["schemas"]["WithdrawnIntakeRequestFromSubmitted"] | components["schemas"]["WithdrawnIntakeRequestFromAccepted"];
        WithdrawnIntakeRequestFromAccepted: {
            /** Format: date-time */
            createdAt: string;
            doctorRequirement: components["schemas"]["DoctorRequirement"];
            healthcareServiceId: components["schemas"]["HealthcareServiceId"];
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            priority: components["schemas"]["IntakeRequestPriority"];
            /** Format: date-time */
            triagedAt: string;
            withdrawalNote: string | null;
            /** Format: date-time */
            withdrawnAt: string;
            withdrawnFrom: {
                /** @enum {string} */
                type: "fromAccepted";
            };
        };
        WithdrawnIntakeRequestFromSubmitted: {
            /** Format: date-time */
            createdAt: string;
            id: components["schemas"]["IntakeRequestId"];
            narrative: string;
            patientId: components["schemas"]["PatientId"];
            withdrawalNote: string | null;
            /** Format: date-time */
            withdrawnAt: string;
            withdrawnFrom: {
                /** @enum {string} */
                type: "fromSubmitted";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
